version: '2'
services:
        uditanshu-1:
                image: confluentinc/cp-zookeeper:latest
                hostname: uditanshu-1
                ports:
                        - "12181:12181"
                environment:
                        ZOOKEEPER_SERVER_ID: 1
                        ZOOKEEPER_CLIENT_PORT: 12181
                        ZOOKEEPER_TICK_TIME: 2000
                        ZOOKEEPER_INIT_LIMIT: 5
                        ZOOKEEPER_SYNC_LIMIT: 2
                        ZOOKEEPER_SERVERS: uditanshu-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
        zookeeper-2:
                image: confluentinc/cp-zookeeper:latest
                hostname: zookeeper-2
                ports:
                        - "22181:22181"
                environment:
                        ZOOKEEPER_SERVER_ID: 2 
                        ZOOKEEPER_CLIENT_PORT: 22181
                        ZOOKEEPER_TICK_TIME: 2000
                        ZOOKEEPER_INIT_LIMIT: 5
                        ZOOKEEPER_SYNC_LIMIT: 2 
                        ZOOKEEPER_SERVERS: uditanshu-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
        zookeeper-3:
                image: confluentinc/cp-zookeeper:latest
                hostname: zookeeper-3
                ports:
                        - "32181:32181"
                environment:
                        ZOOKEEPER_SERVER_ID: 3
                        ZOOKEEPER_CLIENT_PORT: 32181
                        ZOOKEEPER_TICK_TIME: 2000
                        ZOOKEEPER_INIT_LIMIT: 5
                        ZOOKEEPER_SYNC_LIMIT: 2
                        ZOOKEEPER_SERVERS: uditanshu-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
                       
                       
                       
        kafka-1:
                image: confluentinc/cp-kafka:latest
                hostname: kafka-1 
                ports:
                        - "19092:19092"
                depends_on:
                        - uditanshu-1
                        - zookeeper-2
                        - zookeeper-3
                environment:
                        KAFKA_BROKER_ID: 1
                        KAFKA_ZOOKEEPER_CONNECT: uditanshu-1:12181,zookeep-2:12181,zookeeper-3:12181
                        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092 
